apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 18.19.4
    helm:
      releaseName: redis-cluster
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
        image:
          tag: "7.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true