apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # REPLACE THIS WITH YOUR GITHUB REPO URL
    repoURL: [https://github.com/](https://github.com/)<YOUR_GITHUB_USERNAME>/argocd-app-of-apps-demo.git
    targetRevision: HEAD
    # This path points to the folder containing child app YAMLs
    path: applications
  destination:
    server: [https://kubernetes.default.svc](https://kubernetes.default.svc)
    namespace: argocd # The App of Apps itself lives in argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true